
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_NAME = 'SET_CURRENT_USER_NAME';
export const GET_TICKET_REASONS = 'GET_TICKET_REASONS';
export const GET_TICKETS = 'GET_TICKETS';
export const ADD_TICKET = 'ADD_TICKET';
export const VIEW_TICKET = 'VIEW_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_ERRORS = 'GET_ERRORS';


export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
