/* 
    All the action types are defined here
*/

export const GET_TICKET_REASONS = 'GET_TICKET_REASONS';
export const ADD_TICKET_REASONS = 'ADD_TICKET_REASONS';
export const DELETE_TICKET_REASON = 'DELETE_TICKET_REASON';

export const GET_TICKETS = 'GET_TICKETS';
export const ADD_TICKET = 'ADD_TICKET';
export const VIEW_TICKET = 'VIEW_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_ADMIN_TICKETS = 'GET_ADMIN_TICKETS';
export const APPROVE_TICKET = 'APPROVE_TICKET';
export const APPROVE_SINGLE_TICKET = 'APPROVE_SINGLE_TICKET';
export const GET_DRIVER_TICKETS = 'GET_DRIVER_TICKETS';
export const GET_ADMIN_ALL_TICKETS = 'GET_ADMIN_ALL_TICKETS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_NAME = 'SET_CURRENT_USER_NAME';

export const ADD_POLICE = 'ADD_POLICE';
export const GET_ALL_POLICE = 'GET_ALL_POLICE';
export const VIEW_POLICE = 'VIEW_POLICE';
export const DELETE_POLICE = 'DELETE_POLICE';

export const ADD_DRIVER = 'ADD_DRIVER';


export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

export const GET_ERRORS = 'GET_ERRORS';