export const GET_TICKET_REASONS = 'GET_TICKET_REASONS';
export const ADD_TICKET_REASONS = 'ADD_TICKET_REASONS';
export const DELETE_TICKET_REASON = 'DELETE_TICKET_REASON';

export const GET_TICKETS = 'GET_TICKETS';
export const ADD_TICKET = 'ADD_TICKET';
export const VIEW_TICKET = 'VIEW_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_POLICE = 'ADD_POLICE';
export const GET_ALL_POLICE = 'GET_ALL_POLICE';
export const VIEW_POLICE = 'VIEW_POLICE';
export const DELETE_POLICE = 'VIEW_POLICE';

export const GET_ERRORS = 'GET_ERRORS';

